/* Generated by Spinel AOT compiler */
#include "sp_runtime.h"
/* sp_sym intern table */
#define SP_SYM_COUNT 16
static const char *const sp_sym_names[16] = {(&("\xff" "Color")[1]),(&("\xff" "r")[1]),(&("\xff" "uint8")[1]),(&("\xff" "g")[1]),(&("\xff" "b")[1]),(&("\xff" "a")[1]),(&("\xff" "InitWindow")[1]),(&("\xff" "int")[1]),(&("\xff" "str")[1]),(&("\xff" "void")[1]),(&("\xff" "ClearBackground")[1]),(&("\xff" "BeginDrawing")[1]),(&("\xff" "EndDrawing")[1]),(&("\xff" "WindowShouldClose")[1]),(&("\xff" "bool")[1]),(&("\xff" "CloseWindow")[1])};
static const char *sp_sym_to_s(sp_sym id) __attribute__((unused));
static const char *sp_sym_to_s(sp_sym id){if(id>=0&&id<SP_SYM_COUNT)return sp_sym_names[id];return "";}
#define SPS_Color ((sp_sym)0)
#define SPS_r ((sp_sym)1)
#define SPS_uint8 ((sp_sym)2)
#define SPS_g ((sp_sym)3)
#define SPS_b ((sp_sym)4)
#define SPS_a ((sp_sym)5)
#define SPS_InitWindow ((sp_sym)6)
#define SPS_int ((sp_sym)7)
#define SPS_str ((sp_sym)8)
#define SPS_void ((sp_sym)9)
#define SPS_ClearBackground ((sp_sym)10)
#define SPS_BeginDrawing ((sp_sym)11)
#define SPS_EndDrawing ((sp_sym)12)
#define SPS_WindowShouldClose ((sp_sym)13)
#define SPS_bool ((sp_sym)14)
#define SPS_CloseWindow ((sp_sym)15)

/* ---- FFI externs ---- */
#include <stdint.h>
#include <stddef.h>
/* SPINEL_LINK: -lraylib */
/* SPINEL_LINK: -lgdi32 */
/* SPINEL_LINK: -lwinmm */
/* SPINEL_CFLAGS: -I/usr/local/include -L/usr/local/lib */
#include "raylib.h"

/* sp_Class names table */
#define SP_CLASS_COUNT 24
static const char *const sp_class_names[24] = {(&("\xff" "BasicObject")[1]),(&("\xff" "Object")[1]),(&("\xff" "Kernel")[1]),(&("\xff" "Comparable")[1]),(&("\xff" "Enumerable")[1]),(&("\xff" "NilClass")[1]),(&("\xff" "TrueClass")[1]),(&("\xff" "FalseClass")[1]),(&("\xff" "Numeric")[1]),(&("\xff" "Integer")[1]),(&("\xff" "Float")[1]),(&("\xff" "String")[1]),(&("\xff" "Symbol")[1]),(&("\xff" "Array")[1]),(&("\xff" "Hash")[1]),(&("\xff" "Range")[1]),(&("\xff" "Time")[1]),(&("\xff" "Module")[1]),(&("\xff" "Class")[1]),(&("\xff" "Complex")[1]),(&("\xff" "Proc")[1]),(&("\xff" "RAY_Color")[1]),(&("\xff" "Method")[1]),(&("\xff" "RAY")[1])};
static const char *sp_class_to_s(sp_Class c) __attribute__((unused));
static const char *sp_class_to_s(sp_Class c){if(c.cls_id>=0&&c.cls_id<SP_CLASS_COUNT)return sp_class_names[c.cls_id];return "";}
static mrb_bool sp_class_eq(sp_Class a, sp_Class b) __attribute__((unused));
static mrb_bool sp_class_eq(sp_Class a, sp_Class b){return a.cls_id == b.cls_id;}

typedef struct sp_RAY_Color_s sp_RAY_Color;

struct sp_RAY_Color_s {
  mrb_int iv_r;
  mrb_int iv_g;
  mrb_int iv_b;
  mrb_int iv_a;
};

static sp_RAY_Color _ffi_conv_RAY_Color(Color c) {
  sp_RAY_Color obj;
  obj.iv_r = c.r;
  obj.iv_g = c.g;
  obj.iv_b = c.b;
  obj.iv_a = c.a;
  return obj;
}
static Color _ffi_from_RAY_Color(sp_RAY_Color obj) {
  Color c;
  c.r = obj.iv_r;
  c.g = obj.iv_g;
  c.b = obj.iv_b;
  c.a = obj.iv_a;
  return c;
}
static sp_RAY_Color sp_RAY_Color_new(mrb_int lv_r, mrb_int lv_g, mrb_int lv_b, mrb_int lv_a);
static inline void sp_RAY_Color_initialize(sp_RAY_Color *self, mrb_int lv_r, mrb_int lv_g, mrb_int lv_b, mrb_int lv_a);

static sp_RAY_Color sp_RAY_Color_new(mrb_int lv_r, mrb_int lv_g, mrb_int lv_b, mrb_int lv_a) {
  sp_RAY_Color self = {0};
  self.iv_r = lv_r;
  self.iv_g = lv_g;
  self.iv_b = lv_b;
  self.iv_a = lv_a;
  return self;
}

static inline void sp_RAY_Color_initialize(sp_RAY_Color *self, mrb_int lv_r, mrb_int lv_g, mrb_int lv_b, mrb_int lv_a) {
}

int main(int argc,char**argv){
    SP_GC_SAVE();
    sp_RAY_Color lv_bg_color = {0};

    (InitWindow(((int)(400LL)), ((int)(300LL)), (&("\xff" "Spinel Struct Argument Test")[1])), (mrb_int)0);
    lv_bg_color = sp_RAY_Color_new(0LL, 121LL, 241LL, 255LL);
    while ((WindowShouldClose() == FALSE)) {
        sp_redo_1: ;
      (BeginDrawing(), (mrb_int)0);
      (ClearBackground(_ffi_from_RAY_Color(lv_bg_color)), (mrb_int)0);
      (EndDrawing(), (mrb_int)0);
    }
    (CloseWindow(), (mrb_int)0);
  return 0;
}
