/* Generated by Spinel AOT compiler */
#include <ruby.h>
#include "sp_runtime.h"
static const char *sp_sym_to_s(sp_sym id){(void)id;return "";}

/* sp_Class names table */
#define SP_CLASS_COUNT 23
static const char *const sp_class_names[23] = {(&("\xff" "BasicObject")[1]),(&("\xff" "Object")[1]),(&("\xff" "Kernel")[1]),(&("\xff" "Comparable")[1]),(&("\xff" "Enumerable")[1]),(&("\xff" "NilClass")[1]),(&("\xff" "TrueClass")[1]),(&("\xff" "FalseClass")[1]),(&("\xff" "Numeric")[1]),(&("\xff" "Integer")[1]),(&("\xff" "Float")[1]),(&("\xff" "String")[1]),(&("\xff" "Symbol")[1]),(&("\xff" "Array")[1]),(&("\xff" "Hash")[1]),(&("\xff" "Range")[1]),(&("\xff" "Time")[1]),(&("\xff" "Module")[1]),(&("\xff" "Class")[1]),(&("\xff" "Complex")[1]),(&("\xff" "Proc")[1]),(&("\xff" "Method")[1]),(&("\xff" "MyExt")[1])};
static const char *sp_class_to_s(sp_Class c) __attribute__((unused));
static const char *sp_class_to_s(sp_Class c){if(c.cls_id>=0&&c.cls_id<SP_CLASS_COUNT)return sp_class_names[c.cls_id];return "";}
static mrb_bool sp_class_eq(sp_Class a, sp_Class b) __attribute__((unused));
static mrb_bool sp_class_eq(sp_Class a, sp_Class b){return a.cls_id == b.cls_id;}


static inline mrb_int sp_MyExt_cls_add(mrb_int lv_a, mrb_int lv_b);
static inline const char * sp_MyExt_cls_greet(const char * lv_name);

static inline mrb_int sp_MyExt_cls_add(mrb_int lv_a, mrb_int lv_b) {
    SP_GC_SAVE();
    return (lv_a + lv_b);
  return 0;
}

static inline const char * sp_MyExt_cls_greet(const char * lv_name) {
    SP_GC_SAVE();
    SP_GC_ROOT(lv_name);
    return sp_str_concat((&("\xff" "Hello ")[1]), lv_name);
  return (&("\xff")[1]);
}


/* CRuby Extension generated by Spinel */
static VALUE cruby_wrap_MyExt_add(int argc, VALUE *argv, VALUE self) {
  rb_check_arity(argc, 2, 2);
  mrb_int a0 = NUM2INT(argv[0]);
  mrb_int a1 = NUM2INT(argv[1]);
  mrb_int ret = sp_MyExt_cls_add(a0, a1);
  return INT2NUM(ret);
}

static VALUE cruby_wrap_MyExt_greet(int argc, VALUE *argv, VALUE self) {
  rb_check_arity(argc, 1, 1);
  const char * a0 = sp_str_dup_external(StringValueCStr(argv[0]));
  const char * ret = sp_MyExt_cls_greet(a0);
  return rb_utf8_str_new_cstr(ret);
}

void Init_myext(void) {
  VALUE mExt = rb_define_module("MyExt");
  rb_define_singleton_method(mExt, "add", cruby_wrap_MyExt_add, -1);
  rb_define_singleton_method(mExt, "greet", cruby_wrap_MyExt_greet, -1);
}
